---
timestamp: '2025-01-15T22:03:29.913798'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs
        relax-all lp033/mystery__pprob29-err-rate-0-1.yaml
    instance_id: mystery__pprob29-err-rate-0-1
    search_algorithm: dfs
    plan_length: 4
    domain_class: mystery
    instance_name: pprob29-err-rate-0-1
    ground_plan:
    - (overcome jealousy excitement pork neptune uranus)
    - (feast excitement pork broccoli manitoba bavaria)
    - (feast excitement broccoli shrimp pennsylvania alsace)
    - (succumb jealousy excitement shrimp neptune uranus)
    lifted_plan:
    -   - overcome
        - jealousy
        - excitement
        - pork
        - ?neptune
        - uranus
    -   - feast
        - excitement
        - pork
        - ?broccoli
        - manitoba
        - bavaria
    -   - feast
        - excitement
        - broccoli
        - ?shrimp
        - pennsylvania
        - alsace
    -   - succumb
        - ?jealousy
        - excitement
        - shrimp
        - neptune
        - uranus


---
timestamp: '2025-01-15T22:03:30.390659'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 1
    repair: overcome,(harmony ?s1 ?n),precPos,-1


---
timestamp: '2025-01-15T22:05:07.433377'
level: ERROR
issuer: batch_solver
event_type: error
data:
    error_type: MemoryError
    error_message: 'Command ''[''/home/projects/u7899572/conda-envs/main/bin/python3'',
        ''instance_solver.py'', ''dfs'', ''/home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1'',
        ''/home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs relax-all
        lp033/mystery__pprob29-err-rate-0-1.yaml'', ''1000000'', ''mystery__pprob29-err-rate-0-1'',
        ''0.33'', ''unary'']'' died with <Signals.SIGKILL: 9>.'
    stack_trace: "Traceback (most recent call last):\n  File \"batch_solver.py\",\
        \ line 126, in worker\n    result = subprocess.run(cmd, check=True, timeout=params['timeout_seconds'],\n\
        \  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/subprocess.py\"\
        , line 516, in run\n    raise CalledProcessError(retcode, process.args,\n\
        subprocess.CalledProcessError: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',\
        \ 'instance_solver.py', 'dfs', '/home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1',\
        \ '/home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs\
        \ relax-all lp033/mystery__pprob29-err-rate-0-1.yaml', '1000000', 'mystery__pprob29-err-rate-0-1',\
        \ '0.33', 'unary']' died with <Signals.SIGKILL: 9>.\n"
    instance_id: mystery__pprob29-err-rate-0-1
    process_info:
        cmd:
        - /home/projects/u7899572/conda-envs/main/bin/python3
        - instance_solver.py
        - dfs
        - /home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1
        - /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs relax-all
            lp033/mystery__pprob29-err-rate-0-1.yaml
        - '1000000'
        - mystery__pprob29-err-rate-0-1
        - '0.33'
        - unary
        duration: '231.73'
        python_executable: /home/projects/u7899572/conda-envs/main/bin/python3
    stdout: ''
    stderr: ''


