---
timestamp: '2025-01-13T13:55:10.520136'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs
        relax-all lp1/data-network-opt18-strips__pp03-err-rate-0-5.yaml
    instance_id: data-network-opt18-strips__pp03-err-rate-0-5
    search_algorithm: dfs
    plan_length: 12
    domain_class: data-network-opt18-strips
    instance_name: pp03-err-rate-0-5
    ground_plan:
    - (load data-0-6 server3 number3 number8 number0 number3)
    - (load data-0-5 server3 number1 number8 number3 number4)
    - (process data-0-5 data-0-6 data-1-3 script3 server3 number1 number8 number4
        number5)
    - (send data-0-6 server3 server1 number3 number16 number0 number3)
    - (process data-1-3 data-0-5 data-2-2 script11 server3 number3 number8 number5
        number8)
    - (send data-1-3 server3 server1 number1 number16 number3 number4)
    - (process data-1-3 data-0-6 data-2-7 script4 server1 number4 number16 number4
        number8)
    - (send data-2-7 server1 server2 number4 number8 number0 number4)
    - (save data-2-7 number4 server2)
    - (process data-1-3 data-0-6 data-2-2 script5 server1 number3 number16 number8
        number11)
    - (send data-2-2 server1 server2 number3 number8 number4 number7)
    - (save data-2-2 number3 server2)
    lifted_plan:
    -   - load
        - ?data-0-6
        - ?server3
        - ?number3
        - ?number8
        - ?number0
        - ?number3
    -   - load
        - ?data-0-5
        - ?server3
        - ?number1
        - ?number8
        - ?number3
        - ?number4
    -   - process
        - ?data-0-5
        - ?data-0-6
        - ?data-1-3
        - ?script3
        - ?server3
        - ?number1
        - ?number8
        - ?number4
        - ?number5
    -   - send
        - ?data-0-6
        - ?server3
        - ?server1
        - ?number3
        - ?number16
        - ?number0
        - ?number3
    -   - process
        - ?data-1-3
        - ?data-0-5
        - ?data-2-2
        - ?script11
        - ?server3
        - ?number3
        - ?number8
        - ?number5
        - ?number8
    -   - send
        - ?data-1-3
        - ?server3
        - ?server1
        - ?number1
        - ?number16
        - ?number3
        - ?number4
    -   - process
        - ?data-1-3
        - ?data-0-6
        - ?data-2-7
        - ?script4
        - ?server1
        - ?number4
        - ?number16
        - ?number4
        - ?number8
    -   - send
        - ?data-2-7
        - ?server1
        - ?server2
        - ?number4
        - ?number8
        - ?number0
        - ?number4
    -   - save
        - ?data-2-7
        - ?number4
        - ?server2
    -   - process
        - ?data-1-3
        - ?data-0-6
        - ?data-2-2
        - ?script5
        - ?server1
        - ?number3
        - ?number16
        - ?number8
        - ?number11
    -   - send
        - ?data-2-2
        - ?server1
        - ?server2
        - ?number3
        - ?number8
        - ?number4
        - ?number7
    -   - save
        - ?data-2-2
        - ?number3
        - ?server2


---
timestamp: '2025-01-13T13:55:10.526596'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 2
    repair: 'process,(cached ?out ?s),effPos,1

        load,(cached ?d ?s),effPos,1'


---
timestamp: '2025-01-13T14:06:23.932197'
level: ERROR
issuer: batch_solver
event_type: error
data:
    error_type: MemoryError
    error_message: 'Command ''[''/home/projects/u7899572/conda-envs/main/bin/python3'',
        ''instance_solver.py'', ''dfs'', ''/home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1'',
        ''/home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs relax-all
        lp1/data-network-opt18-strips__pp03-err-rate-0-5.yaml'', ''1000000'', ''data-network-opt18-strips__pp03-err-rate-0-5'',
        ''1.0'', ''unary'']'' died with <Signals.SIGABRT: 6>.'
    stack_trace: "Traceback (most recent call last):\n  File \"batch_solver.py\",\
        \ line 126, in worker\n    result = subprocess.run(cmd, check=True, timeout=params['timeout_seconds'],\n\
        \  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/subprocess.py\"\
        , line 516, in run\n    raise CalledProcessError(retcode, process.args,\n\
        subprocess.CalledProcessError: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',\
        \ 'instance_solver.py', 'dfs', '/home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1',\
        \ '/home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs\
        \ relax-all lp1/data-network-opt18-strips__pp03-err-rate-0-5.yaml', '1000000',\
        \ 'data-network-opt18-strips__pp03-err-rate-0-5', '1.0', 'unary']' died with\
        \ <Signals.SIGABRT: 6>.\n"
    instance_id: data-network-opt18-strips__pp03-err-rate-0-5
    process_info:
        cmd:
        - /home/projects/u7899572/conda-envs/main/bin/python3
        - instance_solver.py
        - dfs
        - /home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1
        - /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs relax-all
            lp1/data-network-opt18-strips__pp03-err-rate-0-5.yaml
        - '1000000'
        - data-network-opt18-strips__pp03-err-rate-0-5
        - '1.0'
        - unary
        duration: '675.90'
        python_executable: /home/projects/u7899572/conda-envs/main/bin/python3
    stdout: ''
    stderr: 'terminate called after throwing an instance of ''Minisat22::OutOfMemoryException''

        '


