---
timestamp: '2025-01-13T13:17:52.078223'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs
        relax-all lp1/zenotravel__pp02-err-rate-0-1.yaml
    instance_id: zenotravel__pp02-err-rate-0-1
    search_algorithm: dfs
    plan_length: 8
    domain_class: zenotravel
    instance_name: pp02-err-rate-0-1
    ground_plan:
    - (fly plane1 city0 city1 fl2 fl1)
    - (fly plane1 city1 city2 fl1 fl0)
    - (refuel plane1 city2 fl0 fl1)
    - (board person1 plane1 city2)
    - (fly plane1 city2 city1 fl1 fl0)
    - (refuel plane1 city1 fl0 fl1)
    - (debark person1 plane1 city1)
    - (fly plane1 city1 city2 fl1 fl0)
    lifted_plan:
    -   - fly
        - ?plane1
        - ?city0
        - ?city1
        - ?fl2
        - ?fl1
    -   - fly
        - ?plane1
        - ?city1
        - ?city2
        - ?fl1
        - ?fl0
    -   - refuel
        - ?plane1
        - ?city2
        - ?fl0
        - ?fl1
    -   - board
        - ?person1
        - ?plane1
        - ?city2
    -   - fly
        - ?plane1
        - ?city2
        - ?city1
        - ?fl1
        - ?fl0
    -   - refuel
        - ?plane1
        - ?city1
        - ?fl0
        - ?fl1
    -   - debark
        - ?person1
        - ?plane1
        - ?city1
    -   - fly
        - ?plane1
        - ?city1
        - ?city2
        - ?fl1
        - ?fl0


---
timestamp: '2025-01-13T13:17:52.081720'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 1
    repair: fly,(at ?c2 ?l1),effPos,1


---
timestamp: '2025-01-13T13:29:44.022867'
level: ERROR
issuer: batch_solver
event_type: error
data:
    error_type: MemoryError
    error_message: 'Command ''[''/home/projects/u7899572/conda-envs/main/bin/python3'',
        ''instance_solver.py'', ''dfs'', ''/home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1'',
        ''/home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs relax-all
        lp1/zenotravel__pp02-err-rate-0-1.yaml'', ''1000000'', ''zenotravel__pp02-err-rate-0-1'',
        ''1.0'', ''unary'']'' died with <Signals.SIGABRT: 6>.'
    stack_trace: "Traceback (most recent call last):\n  File \"batch_solver.py\",\
        \ line 126, in worker\n    result = subprocess.run(cmd, check=True, timeout=params['timeout_seconds'],\n\
        \  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/subprocess.py\"\
        , line 516, in run\n    raise CalledProcessError(retcode, process.args,\n\
        subprocess.CalledProcessError: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',\
        \ 'instance_solver.py', 'dfs', '/home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1',\
        \ '/home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs\
        \ relax-all lp1/zenotravel__pp02-err-rate-0-1.yaml', '1000000', 'zenotravel__pp02-err-rate-0-1',\
        \ '1.0', 'unary']' died with <Signals.SIGABRT: 6>.\n"
    instance_id: zenotravel__pp02-err-rate-0-1
    process_info:
        cmd:
        - /home/projects/u7899572/conda-envs/main/bin/python3
        - instance_solver.py
        - dfs
        - /home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1
        - /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs relax-all
            lp1/zenotravel__pp02-err-rate-0-1.yaml
        - '1000000'
        - zenotravel__pp02-err-rate-0-1
        - '1.0'
        - unary
        duration: '713.40'
        python_executable: /home/projects/u7899572/conda-envs/main/bin/python3
    stdout: ''
    stderr: 'terminate called after throwing an instance of ''Minisat22::OutOfMemoryException''

        '


