---
timestamp: '2025-03-17T10:32:43.970143'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/gbfs-unary-ff
        exhaust lp066/freecell__pp02-err-rate-0-3.yaml
    instance_id: freecell__pp02-err-rate-0-3
    search_algorithm: gbfs
    plan_length: 15
    domain_class: freecell
    instance_name: pp02-err-rate-0-3
    ground_plan:
    - (sendtohome cluba diamonda club n1 club0 n0)
    - (sendtohome-b diamonda diamond n1 diamond0 n0 n0 n1)
    - (sendtohome club2 diamond3 club n2 cluba n1)
    - (sendtofree diamond3 spadea n2 n1)
    - (sendtohome-b spadea spade n1 spade0 n0 n1 n2)
    - (sendtohome spade2 club3 spade n2 spadea n1)
    - (sendtohome-b club3 club n3 club2 n2 n2 n3)
    - (sendtofree heart3 diamond2 n1 n0)
    - (sendtohome-b diamond2 diamond n2 diamonda n1 n3 n4)
    - (homefromfreecell diamond3 diamond n3 diamond2 n2 n0 n1)
    - (sendtohome spade3 heart2 spade n3 spade2 n2)
    - (sendtofree heart2 hearta n1 n0)
    - (sendtohome-b hearta heart n1 heart0 n0 n4 n5)
    - (homefromfreecell heart2 heart n2 hearta n1 n0 n1)
    - (homefromfreecell heart3 heart n3 heart2 n2 n1 n2)
    lifted_plan:
    -   - sendtohome
        - cluba
        - diamonda
        - ?club
        - ?n1
        - ?club0
        - ?n0
    -   - sendtohome-b
        - diamonda
        - ?diamond
        - ?n1
        - ?diamond0
        - n0
        - ?n0
        - ?n1
    -   - sendtohome
        - club2
        - ?diamond3
        - ?club
        - n2
        - cluba
        - n1
    -   - sendtofree
        - diamond3
        - ?spadea
        - n2
        - n1
    -   - sendtohome-b
        - spadea
        - ?spade
        - ?n1
        - ?spade0
        - ?n0
        - n1
        - n2
    -   - sendtohome
        - ?spade2
        - club3
        - ?spade
        - n2
        - ?spadea
        - ?n1
    -   - sendtohome-b
        - club3
        - ?club
        - n3
        - club2
        - ?n2
        - ?n2
        - n3
    -   - sendtofree
        - ?heart3
        - ?diamond2
        - n1
        - ?n0
    -   - sendtohome-b
        - ?diamond2
        - ?diamond
        - n2
        - diamonda
        - ?n1
        - ?n3
        - ?n4
    -   - homefromfreecell
        - ?diamond3
        - diamond
        - ?n3
        - ?diamond2
        - n2
        - ?n0
        - n1
    -   - sendtohome
        - ?spade3
        - heart2
        - ?spade
        - ?n3
        - ?spade2
        - ?n2
    -   - sendtofree
        - ?heart2
        - ?hearta
        - ?n1
        - ?n0
    -   - sendtohome-b
        - ?hearta
        - ?heart
        - ?n1
        - ?heart0
        - ?n0
        - n4
        - n5
    -   - homefromfreecell
        - heart2
        - heart
        - n2
        - hearta
        - ?n1
        - ?n0
        - n1
    -   - homefromfreecell
        - ?heart3
        - heart
        - n3
        - heart2
        - ?n2
        - n1
        - ?n2


---
timestamp: '2025-03-17T10:32:43.980767'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 2
    repair: 'sendtohome-b,(successor ?vhomecard ?vhomecard),precPos,-1

        homefromfreecell,(suit ?ncells ?vhomecard),precPos,-1'


---
timestamp: '2025-03-17T10:32:44.027530'
level: ERROR
issuer: batch_solver
event_type: error
data:
    error_type: CalledProcessError
    error_message: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',
        'instance_solver.py', 'configs_exhaustive/gbfs-unary-ff_exhaust_lp066.yaml',
        'freecell__pp02-err-rate-0-3']' returned non-zero exit status 1.
    stack_trace: "Traceback (most recent call last):\n  File \"batch_solver.py\",\
        \ line 119, in worker\n    result = subprocess.run(cmd, check=True, timeout=params['timeout_seconds'],\n\
        \  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/subprocess.py\"\
        , line 516, in run\n    raise CalledProcessError(retcode, process.args,\n\
        subprocess.CalledProcessError: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',\
        \ 'instance_solver.py', 'configs_exhaustive/gbfs-unary-ff_exhaust_lp066.yaml',\
        \ 'freecell__pp02-err-rate-0-3']' returned non-zero exit status 1.\n"
    instance_id: freecell__pp02-err-rate-0-3
    process_info:
        cmd:
        - /home/projects/u7899572/conda-envs/main/bin/python3
        - instance_solver.py
        - configs_exhaustive/gbfs-unary-ff_exhaust_lp066.yaml
        - freecell__pp02-err-rate-0-3
        duration: '2.38'
        python_executable: /home/projects/u7899572/conda-envs/main/bin/python3
    stdout: ''
    stderr: "Traceback (most recent call last):\n  File \"instance_solver.py\", line\
        \ 147, in <module>\n    solve_instance(\n  File \"instance_solver.py\", line\
        \ 122, in solve_instance\n    raise NotImplementedError(\"Search algorithm\
        \ not supported.\")\nNotImplementedError: Search algorithm not supported.\n"


