---
timestamp: '2025-03-17T10:33:24.603430'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/gbfs-unary-ff
        exhaust lp1/freecell__pprobfreecell-3-5-err-rate-0-5.yaml
    instance_id: freecell__pprobfreecell-3-5-err-rate-0-5
    search_algorithm: gbfs
    plan_length: 14
    domain_class: freecell
    instance_name: pprobfreecell-3-5-err-rate-0-5
    ground_plan:
    - (sendtohome ca d3 c n1 c0 n0)
    - (sendtohome da sa d n1 d0 n0)
    - (sendtohome-b sa s n1 s0 n0 n1 n2)
    - (sendtofree c3 s2 n4 n3)
    - (sendtohome-b s2 s n2 sa n1 n2 n3)
    - (sendtohome-b d2 d n2 da n1 n3 n4)
    - (sendtohome-b d3 d n3 d2 n2 n4 n5)
    - (sendtohome-b c2 c n2 ca n1 n5 n6)
    - (homefromfreecell c3 c n3 c2 n2 n3 n4)
    - (sendtofree h2 s3 n4 n3)
    - (sendtohome s3 ha s n3 s2 n2)
    - (sendtohome-b ha h n1 h0 n0 n6 n7)
    - (homefromfreecell h2 h n2 ha n1 n3 n4)
    - (sendtohome-b h3 h n3 h2 n2 n7 n8)
    lifted_plan:
    -   - sendtohome
        - ?ca
        - ?d3
        - ?c
        - ?n1
        - ?c0
        - ?n0
    -   - sendtohome
        - ?da
        - ?sa
        - ?d
        - ?n1
        - ?d0
        - ?n0
    -   - sendtohome-b
        - ?sa
        - ?s
        - ?n1
        - ?s0
        - ?n0
        - ?n1
        - ?n2
    -   - sendtofree
        - ?c3
        - ?s2
        - ?n4
        - ?n3
    -   - sendtohome-b
        - ?s2
        - ?s
        - ?n2
        - ?sa
        - ?n1
        - ?n2
        - ?n3
    -   - sendtohome-b
        - ?d2
        - ?d
        - ?n2
        - ?da
        - ?n1
        - ?n3
        - ?n4
    -   - sendtohome-b
        - ?d3
        - ?d
        - ?n3
        - ?d2
        - ?n2
        - ?n4
        - ?n5
    -   - sendtohome-b
        - ?c2
        - ?c
        - ?n2
        - ?ca
        - ?n1
        - ?n5
        - ?n6
    -   - homefromfreecell
        - ?c3
        - ?c
        - ?n3
        - ?c2
        - ?n2
        - ?n3
        - ?n4
    -   - sendtofree
        - ?h2
        - ?s3
        - ?n4
        - ?n3
    -   - sendtohome
        - ?s3
        - ?ha
        - ?s
        - ?n3
        - ?s2
        - ?n2
    -   - sendtohome-b
        - ?ha
        - ?h
        - ?n1
        - ?h0
        - ?n0
        - ?n6
        - ?n7
    -   - homefromfreecell
        - ?h2
        - ?h
        - ?n2
        - ?ha
        - ?n1
        - ?n3
        - ?n4
    -   - sendtohome-b
        - ?h3
        - ?h
        - ?n3
        - ?h2
        - ?n2
        - ?n7
        - ?n8


---
timestamp: '2025-03-17T10:33:24.611128'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 2
    repair: 'sendtohome-b,(home ?card),effPos,1

        homefromfreecell,(cellspace ?cells),precPos,-1'


---
timestamp: '2025-03-17T10:33:24.638135'
level: ERROR
issuer: batch_solver
event_type: error
data:
    error_type: CalledProcessError
    error_message: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',
        'instance_solver.py', 'configs_exhaustive/gbfs-unary-ff_exhaust_lp1.yaml',
        'freecell__pprobfreecell-3-5-err-rate-0-5']' returned non-zero exit status
        1.
    stack_trace: "Traceback (most recent call last):\n  File \"batch_solver.py\",\
        \ line 119, in worker\n    result = subprocess.run(cmd, check=True, timeout=params['timeout_seconds'],\n\
        \  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/subprocess.py\"\
        , line 516, in run\n    raise CalledProcessError(retcode, process.args,\n\
        subprocess.CalledProcessError: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',\
        \ 'instance_solver.py', 'configs_exhaustive/gbfs-unary-ff_exhaust_lp1.yaml',\
        \ 'freecell__pprobfreecell-3-5-err-rate-0-5']' returned non-zero exit status\
        \ 1.\n"
    instance_id: freecell__pprobfreecell-3-5-err-rate-0-5
    process_info:
        cmd:
        - /home/projects/u7899572/conda-envs/main/bin/python3
        - instance_solver.py
        - configs_exhaustive/gbfs-unary-ff_exhaust_lp1.yaml
        - freecell__pprobfreecell-3-5-err-rate-0-5
        duration: '1.84'
        python_executable: /home/projects/u7899572/conda-envs/main/bin/python3
    stdout: ''
    stderr: "Traceback (most recent call last):\n  File \"instance_solver.py\", line\
        \ 147, in <module>\n    solve_instance(\n  File \"instance_solver.py\", line\
        \ 122, in solve_instance\n    raise NotImplementedError(\"Search algorithm\
        \ not supported.\")\nNotImplementedError: Search algorithm not supported.\n"


