---
timestamp: '2025-03-17T10:33:10.345444'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/gbfs-unary-ff
        exhaust lp1/satellite__pp01-pfile1-err-rate-0-3.yaml
    instance_id: satellite__pp01-pfile1-err-rate-0-3
    search_algorithm: gbfs
    plan_length: 9
    domain_class: satellite
    instance_name: pp01-pfile1-err-rate-0-3
    ground_plan:
    - (switch_on instrument0 satellite0)
    - (turn_to satellite0 groundstation2 phenomenon6)
    - (calibrate satellite0 instrument0 groundstation2)
    - (turn_to satellite0 phenomenon4 groundstation2)
    - (take_image satellite0 phenomenon4 instrument0 thermograph0)
    - (turn_to satellite0 phenomenon6 phenomenon4)
    - (take_image satellite0 phenomenon6 instrument0 thermograph0)
    - (turn_to satellite0 star5 phenomenon6)
    - (take_image satellite0 star5 instrument0 thermograph0)
    lifted_plan:
    -   - switch_on
        - ?instrument0
        - ?satellite0
    -   - turn_to
        - ?satellite0
        - ?groundstation2
        - ?phenomenon6
    -   - calibrate
        - ?satellite0
        - ?instrument0
        - ?groundstation2
    -   - turn_to
        - ?satellite0
        - ?phenomenon4
        - ?groundstation2
    -   - take_image
        - ?satellite0
        - ?phenomenon4
        - ?instrument0
        - ?thermograph0
    -   - turn_to
        - ?satellite0
        - ?phenomenon6
        - ?phenomenon4
    -   - take_image
        - ?satellite0
        - ?phenomenon6
        - ?instrument0
        - ?thermograph0
    -   - turn_to
        - ?satellite0
        - ?star5
        - ?phenomenon6
    -   - take_image
        - ?satellite0
        - ?star5
        - ?instrument0
        - ?thermograph0


---
timestamp: '2025-03-17T10:33:10.348719'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 0
    repair: ''


---
timestamp: '2025-03-17T10:33:10.378531'
level: ERROR
issuer: batch_solver
event_type: error
data:
    error_type: CalledProcessError
    error_message: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',
        'instance_solver.py', 'configs_exhaustive/gbfs-unary-ff_exhaust_lp1.yaml',
        'satellite__pp01-pfile1-err-rate-0-3']' returned non-zero exit status 1.
    stack_trace: "Traceback (most recent call last):\n  File \"batch_solver.py\",\
        \ line 119, in worker\n    result = subprocess.run(cmd, check=True, timeout=params['timeout_seconds'],\n\
        \  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/subprocess.py\"\
        , line 516, in run\n    raise CalledProcessError(retcode, process.args,\n\
        subprocess.CalledProcessError: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',\
        \ 'instance_solver.py', 'configs_exhaustive/gbfs-unary-ff_exhaust_lp1.yaml',\
        \ 'satellite__pp01-pfile1-err-rate-0-3']' returned non-zero exit status 1.\n"
    instance_id: satellite__pp01-pfile1-err-rate-0-3
    process_info:
        cmd:
        - /home/projects/u7899572/conda-envs/main/bin/python3
        - instance_solver.py
        - configs_exhaustive/gbfs-unary-ff_exhaust_lp1.yaml
        - satellite__pp01-pfile1-err-rate-0-3
        duration: '1.70'
        python_executable: /home/projects/u7899572/conda-envs/main/bin/python3
    stdout: ''
    stderr: "Traceback (most recent call last):\n  File \"instance_solver.py\", line\
        \ 147, in <module>\n    solve_instance(\n  File \"instance_solver.py\", line\
        \ 122, in solve_instance\n    raise NotImplementedError(\"Search algorithm\
        \ not supported.\")\nNotImplementedError: Search algorithm not supported.\n"


