---
timestamp: '2025-01-16T09:49:39.117391'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/astar-unary
        relax-all lp033/rovers__pp02-err-rate-0-1.yaml
    instance_id: rovers__pp02-err-rate-0-1
    search_algorithm: astar
    plan_length: 8
    domain_class: rovers
    instance_name: pp02-err-rate-0-1
    ground_plan:
    - (calibrate rover0 camera0 objective0 waypoint0)
    - (take_image rover0 waypoint0 objective1 camera0 low_res)
    - (communicate_image_data rover0 general objective1 low_res waypoint0 waypoint1)
    - (sample_rock rover0 rover0store waypoint0)
    - (communicate_rock_data rover0 general waypoint0 waypoint0 waypoint1)
    - (drop rover0 rover0store)
    - (sample_soil rover0 rover0store waypoint0)
    - (communicate_soil_data rover0 general waypoint0 waypoint0 waypoint1)
    lifted_plan:
    -   - calibrate
        - rover0
        - camera0
        - objective0
        - ?waypoint0
    -   - take_image
        - rover0
        - waypoint0
        - objective1
        - ?camera0
        - low_res
    -   - communicate_image_data
        - rover0
        - general
        - objective1
        - ?low_res
        - waypoint0
        - waypoint1
    -   - sample_rock
        - ?rover0
        - rover0store
        - waypoint0
    -   - communicate_rock_data
        - rover0
        - general
        - ?waypoint0
        - waypoint0
        - waypoint1
    -   - drop
        - rover0
        - rover0store
    -   - sample_soil
        - ?rover0
        - rover0store
        - waypoint0
    -   - communicate_soil_data
        - rover0
        - general
        - waypoint0
        - waypoint0
        - ?waypoint1


---
timestamp: '2025-01-16T09:49:39.717672'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 0
    repair: ''


---
timestamp: '2025-01-16T09:53:08.539470'
level: ERROR
issuer: instance_solver
event_type: error
data: "An error occurred during A* search: 'Node' object has no attribute 'neighbours'.\
    \ Stack trace: Traceback (most recent call last):\n  File \"instance_solver.py\"\
    , line 104, in solve_instance\n    searcher.find_path(logger=logger, log_interval=log_interval)\n\
    \  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py\"\
    , line 75, in find_path\n    self.log_iteration_info(logger, iteration, open_list,\
    \ current_node, final=True, is_goal=True)\n  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py\"\
    , line 37, in log_iteration_info\n    \"current_node\": current_node.to_dict(include_state=False)\n\
    \  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/node.py\"\
    , line 234, in to_dict\n    \"num_neighbours\": len(self.neighbours),\nAttributeError:\
    \ 'Node' object has no attribute 'neighbours'\n"


---
timestamp: '2025-01-16T09:53:09.373997'
level: INFO
issuer: instance_solver
event_type: timer_seconds
data: '418.33'


---
timestamp: '2025-01-16T09:55:42.000713'
level: INFO
issuer: batch_solver
event_type: general
data: 'Subprocess finished successfully. Duration: 653.91 seconds'


