---
timestamp: '2025-01-16T09:49:31.136047'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/astar-unary
        relax-all lp033/rovers__pp04-err-rate-0-3.yaml
    instance_id: rovers__pp04-err-rate-0-3
    search_algorithm: astar
    plan_length: 8
    domain_class: rovers
    instance_name: pp04-err-rate-0-3
    ground_plan:
    - (calibrate rover1 camera0 objective0 waypoint2)
    - (navigate rover1 waypoint2 waypoint1)
    - (take_image rover1 waypoint1 objective0 camera0 high_res)
    - (communicate_image_data rover1 general objective0 high_res waypoint1 waypoint2)
    - (sample_rock rover1 rover1store waypoint1)
    - (communicate_rock_data rover1 general waypoint1 waypoint1 waypoint2)
    - (sample_soil rover0 rover0store waypoint3)
    - (communicate_soil_data rover0 general waypoint3 waypoint3 waypoint2)
    lifted_plan:
    -   - calibrate
        - rover1
        - camera0
        - objective0
        - ?waypoint2
    -   - navigate
        - rover1
        - waypoint2
        - waypoint1
    -   - take_image
        - ?rover1
        - waypoint1
        - objective0
        - camera0
        - high_res
    -   - communicate_image_data
        - ?rover1
        - general
        - objective0
        - ?high_res
        - waypoint1
        - waypoint2
    -   - sample_rock
        - rover1
        - rover1store
        - ?waypoint1
    -   - communicate_rock_data
        - rover1
        - general
        - waypoint1
        - waypoint1
        - ?waypoint2
    -   - sample_soil
        - rover0
        - rover0store
        - waypoint3
    -   - communicate_soil_data
        - rover0
        - general
        - waypoint3
        - ?waypoint3
        - waypoint2


---
timestamp: '2025-01-16T09:49:39.097278'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 1
    repair: take_image,(calibrated ?i ?r),precPos,-1


---
timestamp: '2025-01-16T09:54:54.270803'
level: ERROR
issuer: instance_solver
event_type: error
data: "An error occurred during A* search: 'Node' object has no attribute 'neighbours'.\
    \ Stack trace: Traceback (most recent call last):\n  File \"instance_solver.py\"\
    , line 104, in solve_instance\n    searcher.find_path(logger=logger, log_interval=log_interval)\n\
    \  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py\"\
    , line 75, in find_path\n    self.log_iteration_info(logger, iteration, open_list,\
    \ current_node, final=True, is_goal=True)\n  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py\"\
    , line 37, in log_iteration_info\n    \"current_node\": current_node.to_dict(include_state=False)\n\
    \  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/node.py\"\
    , line 234, in to_dict\n    \"num_neighbours\": len(self.neighbours),\nAttributeError:\
    \ 'Node' object has no attribute 'neighbours'\n"


---
timestamp: '2025-01-16T09:54:54.729737'
level: INFO
issuer: instance_solver
event_type: timer_seconds
data: '557.81'


---
timestamp: '2025-01-16T09:57:14.278233'
level: INFO
issuer: batch_solver
event_type: general
data: 'Subprocess finished successfully. Duration: 802.63 seconds'


