---
timestamp: '2025-01-16T14:51:06.869326'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/astar-unary
        relax-prec lp033/satellite__pp01-pfile1-err-rate-0-3.yaml
    instance_id: satellite__pp01-pfile1-err-rate-0-3
    search_algorithm: astar
    plan_length: 9
    domain_class: satellite
    instance_name: pp01-pfile1-err-rate-0-3
    ground_plan:
    - (switch_on instrument0 satellite0)
    - (turn_to satellite0 groundstation2 phenomenon6)
    - (calibrate satellite0 instrument0 groundstation2)
    - (turn_to satellite0 phenomenon4 groundstation2)
    - (take_image satellite0 phenomenon4 instrument0 thermograph0)
    - (turn_to satellite0 phenomenon6 phenomenon4)
    - (take_image satellite0 phenomenon6 instrument0 thermograph0)
    - (turn_to satellite0 star5 phenomenon6)
    - (take_image satellite0 star5 instrument0 thermograph0)
    lifted_plan:
    -   - switch_on
        - instrument0
        - satellite0
    -   - turn_to
        - satellite0
        - ?groundstation2
        - phenomenon6
    -   - calibrate
        - satellite0
        - instrument0
        - ?groundstation2
    -   - turn_to
        - satellite0
        - phenomenon4
        - groundstation2
    -   - take_image
        - satellite0
        - ?phenomenon4
        - instrument0
        - thermograph0
    -   - turn_to
        - ?satellite0
        - phenomenon6
        - phenomenon4
    -   - take_image
        - satellite0
        - phenomenon6
        - ?instrument0
        - thermograph0
    -   - turn_to
        - satellite0
        - star5
        - phenomenon6
    -   - take_image
        - ?satellite0
        - star5
        - instrument0
        - thermograph0


---
timestamp: '2025-01-16T14:51:07.311808'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 0
    repair: ''


---
timestamp: '2025-01-16T14:51:50.458621'
level: ERROR
issuer: instance_solver
event_type: error
data: "An error occurred during A* search: 'Node' object has no attribute 'neighbours'.\
    \ Stack trace: Traceback (most recent call last):\n  File \"instance_solver.py\"\
    , line 104, in solve_instance\n    searcher.find_path(logger=logger, log_interval=log_interval)\n\
    \  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py\"\
    , line 75, in find_path\n    self.log_iteration_info(logger, iteration, open_list,\
    \ current_node, final=True, is_goal=True)\n  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py\"\
    , line 37, in log_iteration_info\n    \"current_node\": current_node.to_dict(include_state=False)\n\
    \  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/node.py\"\
    , line 234, in to_dict\n    \"num_neighbours\": len(self.neighbours),\nAttributeError:\
    \ 'Node' object has no attribute 'neighbours'\n"


---
timestamp: '2025-01-16T14:51:50.620488'
level: INFO
issuer: instance_solver
event_type: timer_seconds
data: '142.43'


---
timestamp: '2025-01-16T14:53:14.736694'
level: INFO
issuer: batch_solver
event_type: general
data: 'Subprocess finished successfully. Duration: 266.91 seconds'


