> Solving the next problem at: 2024-09-27 08:05:20 UTC
> Search algorithm: bfs
> Instance ID=elevators-opt08-strips/pp02-err-rate-0-5
> Plan length=9
> Domain class: elevators-opt08-strips
> Instance name: pp02-err-rate-0-5
> Ground plan:
['(board p1 slow1-0 n4 n0 n1)', '(move-up-slow slow1-0 n4 n6)', '(leave p1 slow1-0 n6 n1 n0)', '(board p2 slow0-0 n2 n0 n1)', '(move-down-slow slow0-0 n2 n1)', '(leave p2 slow0-0 n1 n1 n0)', '(board p0 fast0 n0 n0 n1)', '(move-up-fast fast0 n0 n4)', '(leave p0 fast0 n4 n1 n0)']
> Lifted plan:
['board', 'move-up-slow', 'leave', 'board', 'move-down-slow', 'leave', 'board', 'move-up-fast', 'leave']
>>>  Vanilla ground repair length:
0

>>>  Vanilla ground repair:


An error occurred during A* search: name 'logger' is not defined
Traceback (most recent call last):
  File "/home/nader/projects/lifted-white-plan-domain-repair/search_partial_grounding/node.py", line 145, in get_neighbors
    possible_groundings = Node.grounder(domain, task, next_action_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nader/projects/lifted-white-plan-domain-repair/search_partial_grounding/action_grounding_tools.py", line 102, in smart_grounder
    subprocess.run(
  File "/home/nader/miniconda3/envs/planning/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/nader/projects/lifted-white-plan-domain-repair/fd2/src/translate/translate.py', 'heuristic_tools/pass_to_grounder_domain.pddl', 'heuristic_tools/pass_to_grounder_task.pddl', '--sas-file', 'heuristic_tools/out.sas']' returned non-zero exit status 31.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nader/projects/lifted-white-plan-domain-repair/instance_solver.py", line 70, in solve_instance
    path, goal_node = searcher.find_path(log_interval=log_interval)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nader/projects/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py", line 49, in find_path
    for neighbor in current_node.get_neighbors():
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nader/projects/lifted-white-plan-domain-repair/search_partial_grounding/node.py", line 148, in get_neighbors
    logger.info(f'>/>/ Current node:\n{self}')
    ^^^^^^
NameError: name 'logger' is not defined. Did you mean: 'self.logger'?

> Time spent on this problem: 0.0 hours = 0.0 minutes = 0.10 seconds
> Subprocess finished.
