---
timestamp: '2025-01-02T01:58:26.477349'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: exp_logs_anu/00 all/mystery__pprob01-err-rate-0-5.yaml
    instance_id: mystery__pprob01-err-rate-0-5
    search_algorithm: bfs
    plan_length: 5
    domain_class: mystery
    instance_name: pprob01-err-rate-0-5
    ground_plan:
    - (overcome abrasion rest pork uranus venus)
    - (feast rest pork lamb alsace quebec)
    - (feast rest lamb flounder surrey pennsylvania)
    - (feast rest flounder rice pennsylvania alsace)
    - (succumb abrasion rest rice uranus venus)
    lifted_plan:
    -   - overcome
        - ?abrasion
        - ?rest
        - ?pork
        - ?uranus
        - ?venus
    -   - feast
        - ?rest
        - ?pork
        - ?lamb
        - ?alsace
        - ?quebec
    -   - feast
        - ?rest
        - ?lamb
        - ?flounder
        - ?surrey
        - ?pennsylvania
    -   - feast
        - ?rest
        - ?flounder
        - ?rice
        - ?pennsylvania
        - ?alsace
    -   - succumb
        - ?abrasion
        - ?rest
        - ?rice
        - ?uranus
        - ?venus


---
timestamp: '2025-01-02T01:58:26.487361'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 0
    repair: ''


---
timestamp: '2025-01-02T01:58:26.661883'
level: ERROR
issuer: node
event_type: error
data:
    current_node:
        depth: 1
        ground_actions:
        - (overcome abrasion rest pork uranus venus)
        repair_set: ''
        g_cost: 0
        h_cost: 0
        f_cost: 0
        next_lifted_action: '[''feast'', ''?rest'', ''?pork'', ''?lamb'', ''?alsace'',
            ''?quebec'']'
        num_neighbours: 0
        first_10_possible_groundings: null
        current_state: '''(province kentucky)'', ''(locale flounder alsace)'', ''(craves
            rest pork)'', ''(locale pear surrey)'', ''(food pear)'', ''(eats pear
            rice)'', ''(locale okra guanabara)'', ''(eats pear okra)'', ''(pain abrasion)'',
            ''(province guanabara)'', ''(eats flounder lamb)'', ''(food pork)'', ''(pain
            depression)'', ''(food lamb)'', ''(attacks quebec guanabara)'', ''(food
            okra)'', ''(locale lamb pennsylvania)'', ''(attacks surrey pennsylvania)'',
            ''(pain hangover)'', ''(craves abrasion pork)'', ''(planet mars)'', ''(planet
            earth)'', ''(province bosnia)'', ''(eats rice pear)'', ''(harmony rest
            uranus)'', ''(attacks pennsylvania alsace)'', ''(orbits earth uranus)'',
            ''(planet uranus)'', ''(eats okra pear)'', ''(province pennsylvania)'',
            ''(fears abrasion rest)'', ''(craves depression flounder)'', ''(attacks
            kentucky bosnia)'', ''(food flounder)'', ''(eats rice flounder)'', ''(orbits
            mars earth)'', ''(eats lamb pork)'', ''(attacks bosnia surrey)'', ''(craves
            hangover rice)'', ''(province alsace)'', ''(eats okra pork)'', ''(planet
            venus)'', ''(orbits uranus venus)'', ''(attacks alsace quebec)'', ''(province
            surrey)'', ''(locale rice bosnia)'', ''(province quebec)'', ''(pleasure
            rest)'', ''(locale pork quebec)'', ''(eats flounder rice)'', ''(eats pork
            okra)'', ''(eats pork lamb)'', ''(harmony rest venus)'', ''(food rice)'',
            ''(eats lamb flounder)'', ''(eats rice rice)'''


---
timestamp: '2025-01-02T01:58:26.676688'
level: ERROR
issuer: instance_solver
event_type: error
data: "An error occurred during A* search: line 41:8 mismatched input '=' expecting\
    \ NAME. Stack trace: Traceback (most recent call last):\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/tarski/io/_fstrips/parser/parser.py\"\
    , line 2532, in predicate\n    self.match(fstripsParser.NAME)\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/antlr4/Parser.py\"\
    , line 118, in match\n    t = self._errHandler.recoverInline(self)\n  File \"\
    /home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/antlr4/error/ErrorStrategy.py\"\
    , line 396, in recoverInline\n    raise InputMismatchException(recognizer)\nantlr4.error.Errors.InputMismatchException:\
    \ None\n\nDuring handling of the above exception, another exception occurred:\n\
    \nTraceback (most recent call last):\n  File \"instance_solver.py\", line 85,\
    \ in solve_instance\n    searcher.find_path(logger=logger, log_interval=log_interval)\n\
    \  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py\"\
    , line 90, in find_path\n    neighbours = current_node.get_neighbors()\n  File\
    \ \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/node.py\"\
    , line 163, in get_neighbors\n    self.possible_groundings = Node.grounder(domain,\
    \ task, next_action_pddl)\n  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/lifted_pddl_grounder.py\"\
    , line 145, in ground_pddl\n    parser.parse_domain(domain_path)\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/lifted_pddl/parser.py\"\
    , line 68, in parse_domain\n    self._reader.parse_domain(domain_path)\n  File\
    \ \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/tarski/io/fstrips.py\"\
    , line 58, in parse_domain\n    self.parse_file(filename, 'domain')\n  File \"\
    /home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/tarski/io/fstrips.py\"\
    , line 54, in parse_file\n    domain_parse_tree, _ = self.parser.parse_file(filename,\
    \ start_rule)\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/tarski/io/_fstrips/reader.py\"\
    , line 43, in parse_file\n    return self._parse_stream(stream, start_rule)\n\
    \  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/tarski/io/_fstrips/reader.py\"\
    , line 51, in _parse_stream\n    tree = getattr(parser, start_rule)()\n  File\
    \ \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/tarski/io/_fstrips/parser/parser.py\"\
    , line 868, in domain\n    self.structureDef()\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/tarski/io/_fstrips/parser/parser.py\"\
    , line 2639, in structureDef\n    self.actionDef()\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/tarski/io/_fstrips/parser/parser.py\"\
    , line 2731, in actionDef\n    self.actionDefBody()\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/tarski/io/_fstrips/parser/parser.py\"\
    , line 3090, in actionDefBody\n    self.effect()\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/tarski/io/_fstrips/parser/parser.py\"\
    , line 4181, in effect\n    self.single_effect()\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/tarski/io/_fstrips/parser/parser.py\"\
    , line 4419, in single_effect\n    self.atomic_effect()\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/tarski/io/_fstrips/parser/parser.py\"\
    , line 4605, in atomic_effect\n    self.atomicTermFormula()\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/tarski/io/_fstrips/parser/parser.py\"\
    , line 3641, in atomicTermFormula\n    self.predicate()\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/tarski/io/_fstrips/parser/parser.py\"\
    , line 2535, in predicate\n    self._errHandler.reportError(self, re)\n  File\
    \ \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/antlr4/error/ErrorStrategy.py\"\
    , line 126, in reportError\n    self.reportInputMismatch(recognizer, e)\n  File\
    \ \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/antlr4/error/ErrorStrategy.py\"\
    , line 264, in reportInputMismatch\n    recognizer.notifyErrorListeners(msg, e.offendingToken,\
    \ e)\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/antlr4/Parser.py\"\
    , line 314, in notifyErrorListeners\n    listener.syntaxError(self, offendingToken,\
    \ line, column, msg, e)\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/antlr4/error/ErrorListener.py\"\
    , line 60, in syntaxError\n    delegate.syntaxError(recognizer, offendingSymbol,\
    \ line, column, msg, e)\n  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/site-packages/tarski/io/_fstrips/reader.py\"\
    , line 505, in syntaxError\n    raise ParsingError(msg)\ntarski.io._fstrips.reader.ParsingError:\
    \ line 41:8 mismatched input '=' expecting NAME\n"


---
timestamp: '2025-01-02T01:58:26.681640'
level: INFO
issuer: instance_solver
event_type: timer_seconds
data: '3.66'


